# Generated by Django 3.1.3 on 2021-01-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_admin_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='name',
        ),
    ]
