# Generated by Django 3.1.3 on 2021-01-19 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210119_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_doc',
            name='password',
        ),
        migrations.AddField(
            model_name='admin_doc',
            name='age',
            field=models.IntegerField(default=25),
        ),
        migrations.AddField(
            model_name='admin_doc',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_doc',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_doc',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_doc',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.user'),
            preserve_default=False,
        ),
    ]
