# Generated by Django 3.1.3 on 2021-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210119_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='name',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='admin_doc',
            name='department',
        ),
        migrations.RemoveField(
            model_name='admin_doc',
            name='name',
        ),
        migrations.AddField(
            model_name='admin_doc',
            name='department_doc',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin_doc',
            name='name1',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
